### ISSUE TITLE
Unable to connect to the uget-chrome-wrapper

### ISSUE THREAD

**Issue by UncleInf** [slgobinath/uget-chrome-wrapper#15]
When using chrome or opera getting error:
`Error: Unable to connect to the uget-chrome-wrapper`

Windows 7 x64
Chrome 56
Plugin reinstalled v2
Extention reinstalled v2

Before updating extention worked on chrome.

**Comment by slgobinath** [comment]
Hi,
Have you updated the Python to 3.4 or latest? That is the major change with v 2.

**Comment by UncleInf** [comment]
Yes, I have python3 installed
```
python --version
Python 3.5.1
```

Running: `python uget-chrome-wrapper.py` launches without problem.

**Comment by slgobinath** [comment]
Then it seems to be a problem. Please check if you double click the `C:\Program Files (x86)\uget-chrome-wrapper\uget-chrome-wrapper.py` whether it open in Python console or text editor.
Meanwhile, I will test it on Windows 7 (I have tested on Windows 10 64bit. It is working properly)

Thanks

**Comment by slgobinath** [comment]
Thanks for reporting the bug. This bug occurs in lower versions of Python due to my fault. I'll release the fix soon. Sorry for the trouble.

**Comment by slgobinath** [comment]
A new version [uget-chrome-wrapper_2.0.2.exe](https://github.com/slgobinath/uget-chrome-wrapper/releases/download/v2.0.0/uget-chrome-wrapper_2.0.0.exe) is released. Could you please let me know whether you problem has been resolved with this fix.

Thanks

**Comment by UncleInf** [comment]
I've tried the updated version, but the problem remains. 

Tried with opera (`uGet Integration Version 2.0.3`) and chrome on win7 x64. Updated python script `VERSION = "2.0.2"`

**Comment by slgobinath** [comment]
Hi,
In the previous script, there was a problem with lower Python version but with the new version, it should be fixed. Please ensure that Python is the default application to open .py extensions. In other words, if you double click the `uget-chrome-wrapper.py`, it should run as a Python application.

**Comment by UncleInf** [comment]
Hello,

I've double checked everything and it seems like the problem remains, atleast on my system. Double clicking `uget-chrome-wrapper.py` opens up cmd window for a brief moment, also on properties windows say it opens up with: python.exe

**Comment by slgobinath** [comment]
Alright. I'll try my best to reproduce this issue and let you know.

**Comment by slgobinath** [comment]
Hi @UncleInf,
I faced a similar problem with Firefox in Windows and changed the way to connect the Python script in [v2.0.4](https://github.com/slgobinath/uget-chrome-wrapper/releases/tag/v2.0.4). Could you please test the new version and let me know whether it resolves your problem.

Thanks

**Comment by nithinmurali** [comment]
Hi, 
  I am facing same issue in Ubuntu 14.04, Chrome 56. I have python3.x installed (but not default).

**Comment by slgobinath** [comment]
Hi @nithinmurali,
I couldn't reproduce this in my Ubuntu 14.04 VM with Python 3.4.3.
```
python3 -V
```
Still I am unable to reproduce in Windows 10.

**Comment by beew** [comment]
Same problem here. Ubuntu 16.04 fully up to date. Tried on both Chrome (59.0.3071.86)  and Opera (45.0) have python 3.5.1 installed from the standard repository.

**Comment by slgobinath** [comment]
@beew,
Thanks for reporting the bug but I am clueless on the issue as I am unable to reproduce in my testing environments. Could you please enable logging by following these steps and share the log in the comment.
1. Open uget-chrome-wrapper
```
sudo gedit /usr/bin/uget-chrome-wrapper
```
2. Uncomment the following two lines and save the changes
```
# log_file_path = join(expanduser('~'), 'uget-chrome-wrapper.log')
# logging.basicConfig(format='%(asctime)s [%(levelname)s]: %(message)s', filename=log_file_path, filemode='a', level=logging.DEBUG)
```
After uncommenting, it should become:
```
log_file_path = join(expanduser('~'), 'uget-chrome-wrapper.log')
logging.basicConfig(format='%(asctime)s [%(levelname)s]: %(message)s', filename=log_file_path, filemode='a', level=logging.DEBUG)
```
3. Open the browser and share the content of `~/uget-chrome-wrapper.log`

**Comment by beew** [comment]
Hi, I am terribly sorry. I have goofed. I thought it is just a browser addon like downthemall for firefox, so I have just installed the uget integration via the browser. I didn't know I have to install uget-chrome-wrapper separately.  Now I have done that and the error goes away.

**Comment by slgobinath** [comment]
Hi @beew,
No worries :-).

@UncleInf and @nithinmurali could you please send me the log in your system?

Thanks

**Comment by UncleInf** [comment]
I have tried latest release and my problem seem to be gone - very good! Do you still need logs from my system?

**Comment by slgobinath** [comment]
@UncleInf no thanks for updating.
I am closing this issue.

**Comment by nithinmurali** [comment]
I got it working too. Thanks :)

**Comment by cacophobe** [comment]
Thank you for making this :-)

I am facing this issue on Firefox, even though it works with the same installation configuration, on the same computer, in Chromium. 

- Firefox: 54.0, 64 bit, Multiprocess enabled
- Python: 3.6.1
- Uget Chrome Wrapper: 2.0.4.0
- OS: Windows 10, 64-bit

Any help would be greatly appreciated.

**Comment by saidbakr** [comment]
I have the same issue with Chrome Version `59.0.3071.115 (Official Build) (64-bit)` On Ubuntu 16.04 64bit with Xfce4. uGet Chrome version 2.0.4 and uGet 2.0.9

**Comment by slgobinath** [comment]
@saidbakr how dod you install the uget-chrome-wrapper?
Could you please uninstall it and install again and let me know the result.

**Comment by slgobinath** [comment]
@cacophobe your bug report has been confirmed. I will check this and release the fix soon.

Thanks for reporting.

**Comment by KhogaEslam** [comment]
@slgobinath
I have same problem too
on `Ubuntu 17.04` and `chrome` browser

**Comment by slgobinath** [comment]
@KhogaEslam Could you please enable logging by following these steps and share the log in the comment.
1. Open uget-chrome-wrapper
```
sudo gedit /usr/bin/uget-chrome-wrapper
```
2. Uncomment the following two lines and save the changes
```
# log_file_path = join(expanduser('~'), 'uget-chrome-wrapper.log')
# logging.basicConfig(format='%(asctime)s [%(levelname)s]: %(message)s', filename=log_file_path, filemode='a', level=logging.DEBUG)
```
After uncommenting, it should become:
```
log_file_path = join(expanduser('~'), 'uget-chrome-wrapper.log')
logging.basicConfig(format='%(asctime)s [%(levelname)s]: %(message)s', filename=log_file_path, filemode='a', level=logging.DEBUG)
```
3. Open the browser and share the content of `~/uget-chrome-wrapper.log`

**Comment by slgobinath** [comment]
@cacophobe, @KhogaEslam, @saidbakr I have opened a new issue #20  with clear instructions. If you couldn't resolve the problem, please share the _uGet version_, _Browser name and version_ and the _Operating System with version_ along with the **log**.

This issue is closed permanently.

**Comment by mbol8309** [comment]
i'm getting the same error, i have installed fedora 25, vivaldi 1.10.867.48 (Stable channel) (64-bit), followed the steps in installation guide, enable logging and there is no file uget-chrome-wrapper.log. any tips?

**Comment by slgobinath** [comment]
Hi @mbol8309,

Please check whether you have the file [com.javahelps.ugetchromewrapper.json](https://github.com/slgobinath/uget-chrome-wrapper/blob/master/uget-chrome-wrapper/conf/com.javahelps.ugetchromewrapper.json) in 
```
/etc/chromium/native-messaging-hosts/com.javahelps.ugetchromewrapper.json
```

**Comment by mbol8309** [comment]
yes : ll /etc/chromium/native-messaging-hosts/com.javahelps.ugetchromewrapper.json 
-rw-r--r-- 1 root root 1177 Jul 18 22:50 /etc/chromium/native-messaging-hosts/com.javahelps.ugetchromewrapper.json

**Comment by slgobinath** [comment]
The parent directory is not created by default. If all the following files are available, it should work in Vivaldi. 
 - `/etc/chromium/native-messaging-hosts/com.javahelps.ugetchromewrapper.json`
 - `/usr/bin/uget-chrome-wrapper`
- The `uGet Intergation` extension

(Need to restart the browser after installing the files)

If it doesn't resolve the problem, I will test it in my Fedora virtual system and let you know.

**Comment by mbol8309** [comment]
please test or tell me how to enable vivaldi log, so i can search my self, i know is not your concern vivaldi logs, but i followed the steps and restarted vivaldi several times and enable logging but there is no log file. any tips would help.

PD: sorry for my english, my natural language is spanish

**Comment by slgobinath** [comment]
Run Vivaldi from the Terminal using the following command:
```
vivaldi --remote-debugging-port=9222
```
Then visit this URL in the browser: [localhost:9222](http://localhost:9222) and click on the `uGet Integration` extension link.

No worries about the language. I am also not a native English speaker and have the same problem :-)

**Comment by mbol8309** [comment]
for what i see, he can't find the wrapper 
```
function getInfo() {
    if (ugetWrapperNotFound || !ugetChromeWrapperVersion) {
        return "Error: Unable to connect to the uget-chrome-wrapper";
```
but i don't have the experience in debugging extensions, tomorrow i'll give another try

**Comment by slgobinath** [comment]
Hi @mbol8309,
I have tested it on Fedora 26.
I have installed the `com.javahelps.ugetchromewrapper.json` in the following path which is for Chrome but working for Vivaldi as well.
```
/etc/opt/chrome/native-messaging-hosts/com.javahelps.ugetchromewrapper.json
```
Please try to add the file in the `/etc/opt/chrome/native-messaging-hosts` and check the output.

**Comment by mbol8309** [comment]
more testing....:
in developer mode, when i tried to run 
`sendMessageToHost('test')`
i get the following error:
```
Uncaught Error: Invocation of form runtime.sendNativeMessage(string, string, function) doesn't match definition runtime.sendNativeMessage(string application, object message, optional function responseCallback)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:112)
    at Object.<anonymous> (extensions::binding:411)
    at sendMessageToHost (background.js:359)
    at <anonymous>:1:1
```
maybe the erro is around here, because in the function callback is where 
`ugetWrapperNotFound = (response==null)`

**Comment by mbol8309** [comment]
i need a way to debug the extension or undestand how it works so I can fix or see what is the problem. if can be possible write me to mbol8309@gmail.com so we did't full this post of developer talk.

**Comment by slgobinath** [comment]
@mbol8309,
I have released a script to install uget-chrome-wrapper. Could you please try this solution:
```
wget https://raw.githubusercontent.com/slgobinath/uget-chrome-wrapper/master/build/linux/install_uget_chrome_wrapper.sh
sudo sh install_uget_chrome_wrapper.sh
```
Install the extension and restart the browser.
